# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 8
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/FDu/second1/DL/lab/picture/picture.cache/wt [current_project]
set_property parent.project_path E:/FDu/second1/DL/lab/picture/picture.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/FDu/second1/DL/lab/picture/picture.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files e:/FDu/second1/DL/week13/nailong.coe
read_verilog -library xil_defaultlib -sv {
  E:/FDu/second1/DL/week13/示例代码/ping-pong/ping-pong/ping-pong.srcs/sources_1/imports/new/VGA640x480.sv
  E:/FDu/second1/DL/week13/示例代码/ping-pong/ping-pong/ping-pong.srcs/sources_1/new/clk60Hz.sv
  E:/FDu/second1/DL/week13/示例代码/ping-pong/ping-pong/ping-pong.srcs/sources_1/imports/new/clkDiv.sv
  E:/FDu/second1/DL/lab/picture/picture.srcs/sources_1/new/picture.sv
  E:/FDu/second1/DL/lab/picture/picture.srcs/sources_1/new/picture_top.sv
}
read_ip -quiet e:/FDu/second1/DL/lab/picture/picture.srcs/sources_1/ip/Draw/Draw.xci
set_property used_in_implementation false [get_files -all e:/FDu/second1/DL/lab/picture/picture.srcs/sources_1/ip/Draw/Draw_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/FDu/second1/DL/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files E:/FDu/second1/DL/Nexys4DDR_Master.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top picture_top -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef picture_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file picture_top_utilization_synth.rpt -pb picture_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
