# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/FDu/second1/DL/lab/SVGA/SVGA.srcs/sources_1/ip/clk50MHz/clk50MHz.xci
# IP: The module: 'clk50MHz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FDu/second1/DL/lab/SVGA/SVGA.srcs/sources_1/ip/clk50MHz/clk50MHz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk50MHz'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/FDu/second1/DL/lab/SVGA/SVGA.srcs/sources_1/ip/clk50MHz/clk50MHz.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk50MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/FDu/second1/DL/lab/SVGA/SVGA.srcs/sources_1/ip/clk50MHz/clk50MHz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk50MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: e:/FDu/second1/DL/lab/SVGA/SVGA.srcs/sources_1/ip/clk50MHz/clk50MHz.xci
# IP: The module: 'clk50MHz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FDu/second1/DL/lab/SVGA/SVGA.srcs/sources_1/ip/clk50MHz/clk50MHz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk50MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/FDu/second1/DL/lab/SVGA/SVGA.srcs/sources_1/ip/clk50MHz/clk50MHz.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk50MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/FDu/second1/DL/lab/SVGA/SVGA.srcs/sources_1/ip/clk50MHz/clk50MHz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk50MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
