# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/FDu/second1/DL/lab/music/music.srcs/sources_1/ip/SuperMario/SuperMario.xci
# IP: The module: 'SuperMario' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FDu/second1/DL/lab/music/music.srcs/sources_1/ip/SuperMario/SuperMario_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SuperMario'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/FDu/second1/DL/lab/music/music.srcs/sources_1/ip/SuperMario/SuperMario.xci
# IP: The module: 'SuperMario' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FDu/second1/DL/lab/music/music.srcs/sources_1/ip/SuperMario/SuperMario_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SuperMario'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
